author: King6887
database: true
description: Plugin to handle player invites to the Cursecraft server.
main: com.king6887.plugins.ccinvites.CCInvites
name: CCInvites
startup: postworld
version: ${project.version}
commands:
  invite:
    aliases: [inv, cciinvite]
    description: Invite someone to the server.
    permission: ccinvites.invite
    usage: /<command> [player] [note] to invite player, note is optional.
  myinvites:
    aliases: [myinvs, ccimyinvites]
    description: Lists the number of invites you have.
    permission: ccinvites.myinvites
    usage: /<command> [player] to get your or someone elses (op only) invite status.
  cci:
    description: Admin and Help functions for ccinvites.
    permission: ccinvites.invite
    usage: /<command> help for detailed usage.
permissions:
  ccinvites.*:
    description: Gives access to all CCInvites commands.
    children:
      ccinvites.invite: true
      ccinvites.myinvites: true
      ccinvites.myinvites.others: true
      ccinvites.admin: true
  ccinvites.invite:
    description: Allows you to invite others to the server.
    default: true
  ccinvites.myinvites:
    description: Allows you to view your invite status.
    default: true
  ccinvites.myinvites.others:
    description: Allows you to view other peoples invite status.
    default: op
  ccinvites.admin:
    description: Allows you to use all cci admin commands.
    children:
      ccinvites.admin.update: true
      ccinvites.admin.import: true
      ccinvites.admin.extras: true
  ccinvites.admin.update:
    description: Allows you to force update players invites.
    default: op
  ccinvites.admin.import:
    description: Allows you to import from csv file.
    default: op
  ccinvites.admin.extras:
    description: Allows you to allocate extra invites to players.
    default: op